---
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          path: releases/*.deb
